name: default
model_class: model.din.Din

data_args:
 train_limit: 10000
 train:
  meta: /root/lanyun-tmp/dataset/amazon_book/item-info
  codebooks: /root/lanyun-tmp/dataset/amazon_book/
  data: /root/lanyun-tmp/dataset/amazon_book/local_train_splitByUser
 eval_limit: 1000
 eval:
  meta: /root/lanyun-tmp/dataset/amazon_book/item-info
  codebooks: /root/lanyun-tmp/dataset/amazon_book/
  data: /root/lanyun-tmp/dataset/amazon_book/local_test_splitByUser

training_args:
  seed: 42
  train_batch_size: 8
  eval_batch_size: 16
  from_scratch: True
  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.01
  loss: binary_crossentropy
  metrics:
   - binary_accuracy
   - Precision
   - Recall
   - AUC
  num_epochs: 1
  warmup_ratio: 0.1
  train_steps_per_epoch: 12500
  save_path: /root/lanyun-tmp/model/din/inference
  ckpt_path: /root/lanyun-tmp/model/din/checkpoints/best_model.keras


model_args:
  num_users: 543060
  num_items: 367983
  num_categories: 1601
  embedding_dim: 32
  hidden_size: 36
  use_negative: False
  activation: dice
  softmax_logits: False





